spring:
  profiles:
    active:
      - chaos-monkey

management:
  endpoint:
    chaosmonkey:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,chaosmonkey

springdoc:
  show-actuator: true
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

